### PR TITLE
standardization of the translation of key

### PR DESCRIPTION
**Pull request by flug**
just to have the translation string with the same case

### CODE REVIEW

**Comment by greg0ire** [comment]
"the same square"?

**Comment by flug** [comment]
Sorry, my English is as bad as ever  :neckbeard:

**Comment by greg0ire** [comment]
No problem :) Did you mean "the same case"?

**Comment by flug** [comment]
"the same character case." Maybe ? :D

**Comment by greg0ire** [comment]
Ok this looks better. Now, what if people want to use a different standardization strategy? What if people do not use i18n at all?

**Comment by flug** [comment]
Yes! Hum please wait, I do a new pull request for this possibility :+1:

**Comment by greg0ire** [comment]
Do not do a new pr, just overwrite this one with push -f

**Comment by flug** [comment]
Yes

**Comment by flug** [comment]
Lol. Ok wait ;)

**Comment by greg0ire** [comment]
DI is hard to achieve with static methods but not impossible :)

**Comment by flug** [comment]
I have modified my commit, but you travis is failed with php ngithly 7.10, A priori a problem in downloading the executable XD

**Comment by greg0ire** [comment]
ping @flug

**Comment by flug** [comment]
Yes, I try to find an answer in the days and months ahead :100:

**Pull request closed without merging**
